SHELL := /bin/bash
REPOS="feed_the_troll_msgs" "feed_the_troll"
REPOS="feed_the_troll"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=kinetic
SOURCE_BRANCH=release/0.1-indigo-kinetic

include ../Makefile

