SHELL := /bin/bash
REPOS="py_trees" "py_trees_msgs" "py_trees_ros"
REPOS="py_trees_ros"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/stonier
TRACK=kinetic
SOURCE_BRANCH=release/0.5-kinetic

include ../Makefile

