SHELL := /bin/bash
REPOS="py_trees" "py_trees_msgs" "py_trees_ros" "rqt_py_trees"
REPOS="rqt_py_trees"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/stonier
TRACK=kinetic
SOURCE_BRANCH=release/0.5-kinetic

include ../Makefile

