SHELL := /bin/bash
#REPOS="ecl_tools" "ecl_lite" "ecl_core" "ecl_manipulation" "ecl_navigation"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=melodic

REPOS="ecl_core"
SOURCE_BRANCH=release/0.62-melodic

include ../Makefile

