SHELL := /bin/bash
#REPOS="ecl_tools" "ecl_lite" "ecl_core" "ecl_manipulation" "ecl_navigation"
REPOS="ecl_lite"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=lunar
SOURCE_BRANCH=release/0.61-lunar

include ../Makefile

