SHELL := /bin/bash
#REPOS="yocs_msgs" "yujin_ocs"
SRC_GIT=https://github.com/yujinrobot
REL_GIT=https://github.com/yujinrobot-release
TRACK=melodic

REPOS="yocs_msgs"
SOURCE_BRANCH=release/0.7-melodic
#REPOS="yujin_ocs"
#SOURCE_BRANCH=release/0.8-melodic

include ../Makefile

