SHELL := /bin/bash
#REPOS="yocs_msgs" "yujin_ocs"
REPOS="yujin_ocs"
SRC_GIT=https://github.com/yujinrobot
REL_GIT=https://github.com/yujinrobot-release
TRACK=melodic
#SOURCE_BRANCH=release/0.7-melodic
SOURCE_BRANCH=release/0.8-melodic

include ../Makefile

