SHELL := /bin/bash
#REPOS="kobuki_msgs" "kobuki_core" "kobuki" "yujin_ocs"
REPOS="kobuki"
SRC_GIT=https://github.com/yujinrobot
REL_GIT=https://github.com/yujinrobot-release
TRACK=melodic
# kobuki_core
# SOURCE_BRANCH=melodic
# kobuki_msgs, kobuki
SOURCE_BRANCH=release/0.7-melodic

include ../Makefile

