SHELL := /bin/bash
#REPOS="kobuki_core" "kobuki_msgs" "kobuki"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=eloquent

REPOS="kobuki_core"
SOURCE_BRANCH=release/0.8.x

#REPOS="kobuki_msgs"
#SOURCE_BRANCH=release/0.8.x


include ../Makefile

