SHELL := /bin/bash
#REPOS="kobuki_core" "kobuki_msgs" "kobuki"
SRC_GIT=https://github.com/stonier
TRACK=eloquent

#REPOS="kobuki_core"
#SOURCE_BRANCH=release/0.8.x
#REL_GIT=https://github.com/yujinrobot-release

REPOS="kobuki_ros_interfaces"
SOURCE_BRANCH=release/1.0.x
REL_GIT=https://github.com/stonier


include ../Makefile

