SHELL := /bin/bash
#REPOS="kobuki_core" "kobuki_ros_interfaces" "kobuki"
SRC_GIT=https://github.com/kobuki-base
REL_GIT=https://github.com/stonier
TRACK=eloquent

#REPOS="kobuki_core"
#SOURCE_BRANCH=release/1.0.x

#REPOS="kobuki_ros_interfaces"
#SOURCE_BRANCH=release/1.0.x

#REPOS="kobuki_ftdi"
#SOURCE_BRANCH=release/1.0.x

REPOS="kobuki_ros"
SOURCE_BRANCH=release/1.0.x

include ../Makefile

