SHELL := /bin/bash
REPOS="zeroconf_msgs" "zeroconf_avahi_suite"
REPOS="zeroconf_msgs"
#REPOS="zeroconf_avahi_suite"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=melodic
SOURCE_BRANCH=indigo

include ../Makefile

