SHELL := /bin/bash
REPOS="feed_the_troll_msgs" "feed_the_troll"
REPOS="cost_map"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/stonier
TRACK=kinetic
SOURCE_BRANCH=release/0.3-indigo-kinetic

include ../Makefile

