SHELL := /bin/bash
#REPOS="py_trees" "py_trees_ros_interfaces" "py_trees_ros" "rqt_py_trees"
SRC_GIT=https://github.com/splintered-reality
REL_GIT=https://github.com/stonier
TRACK=dashing

REPOS="py_trees"
SOURCE_BRANCH=release/1.3.x

#REPOS="py_trees_ros_interfaces"
#SOURCE_BRANCH=release/1.2.x

#REPOS="py_trees_ros"
#SOURCE_BRANCH=release/1.1.x

#REPOS="py_trees_ros_tutorials"
#SOURCE_BRANCH=release/1.0.x

#REPOS="py_trees_js"
#SOURCE_BRANCH=release/0.5.x

#REPOS="py_trees_ros_viewer"
#SOURCE_BRANCH=release/0.1.x

include ../Makefile

