SHELL := /bin/bash
#REPOS="py_trees" "py_trees_msgs" "py_trees_ros" "rqt_py_trees"
REPOS="py_trees"
# REPOS="py_trees_msgs"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/stonier
TRACK=crystal
SOURCE_BRANCH=release/1.0.x
#SOURCE_BRANCH=release/0.4.x

include ../Makefile

