SHELL := /bin/bash
#REPOS="py_trees" "py_trees_ros_interfaces" "py_trees_ros" "rqt_py_trees"
SRC_GIT=https://github.com/splintered-reality
REL_GIT=https://github.com/stonier
TRACK=dashing

#REPOS="py_trees"
#SOURCE_BRANCH=release/1.2.x

REPOS="py_trees_ros_interfaces"
SOURCE_BRANCH=release/1.1.x

include ../Makefile

