SHELL := /bin/bash
#REPOS="ecl_tools" "ecl_lite" "ecl_core" "ecl_manipulation" "ecl_navigation"
REPOS="ecl_core"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=crystal
SOURCE_BRANCH=release/1.0-crystal

include ../Makefile

