SHELL := /bin/bash
#REPOS="ecl_tools" "ecl_lite" "ecl_core"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=dashing

#REPOS="ecl_tools"
#REPOS="ecl_lite"
REPOS="ecl_core"
SOURCE_BRANCH=release/1.0.x


include ../Makefile

