SHELL := /bin/bash
REPOS="py_trees" "py_trees_msgs" "py_trees_ros" "rqt_py_trees"
REPOS="py_trees_msgs"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/stonier
TRACK=kinetic
# py trees and py_trees_ros
SOURCE_BRANCH=release/0.5-kinetic
# rqt_py_trees
SOURCE_BRANCH=release/0.3-kinetic

include ../Makefile

