SHELL := /bin/bash
REPOS="py_trees" "py_trees_msgs" "py_trees_ros" "rqt_py_trees"
REPOS="rqt_py_trees"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/stonier
#TRACK=kinetic
TRACK=melodic

# py_trees_msgs
#SOURCE_BRANCH=release/0.3-melodic

# py trees
#SOURCE_BRANCH=release/0.5-kinetic
#SOURCE_BRANCH=release/0.6-melodic

# py_trees_ros
#SOURCE_BRANCH=release/0.5-kinetic
#SOURCE_BRANCH=release/0.5-melodic

# rqt_py_trees
#SOURCE_BRANCH=release/0.3-kinetic
SOURCE_BRANCH=release/0.3-melodic

include ../Makefile

