SHELL := /bin/bash
REPOS="py_trees" "py_trees_msgs" "py_trees_ros" "rqt_py_trees"
SRC_GIT=https://github.com/splintered-reality
REL_GIT=https://github.com/stonier
#TRACK=kinetic
#TRACK=melodic
TRACK=noetic

# py_trees_msgs
REPOS="py_trees_msgs"
SOURCE_BRANCH=release/0.3.x

# py trees
#REPOS="py_trees"
#SOURCE_BRANCH=release/0.5.x  # kinetic
#SOURCE_BRANCH=release/0.6.x  # melodic

# py_trees_ros
#REPOS=py_trees_ros
#SOURCE_BRANCH=release/0.5.x

# rqt_py_trees
#REPOS="rqt_py_trees"
#SOURCE_BRANCH=release/0.3-${TRACK}
#SOURCE_BRANCH=release/0.3-${TRACK}

include ../Makefile

